### ISSUE TITLE
런타임에러 시 에러 이유를 알람창에 함께 띄우기

### ISSUE THREAD

**Issue by sawol** [sawol/Baekjoon-Alarm#1]
** 추가 기능에 대한 설명 [필수] **
  
런타임 에러 발생 시 백준에서는 "런타임 에러 (ValueError)" 이런 식으로 에러 발생 이유를 알려줍니다.  
현재 버전은 "런타임 에러"만 알려주고 어떤 이유인지는 알려주지 않습니다.  
"런타임 에러" -> "런타임 에러 (ValueError)"로 추가 정보를 알려주는 기능이 필요합니다.

** 설명에 대한 추가 이미지 [옵션] **
추가 기능을 설명할 적절한 이미지가 있다면 첨부해주세요.

** 해당 기능이 필요한 이유 [필수] **
   
이유까지 알려주면 좋을 거 같다는 의견이 있어서 추가 기능 요청을 합니다.

**Comment by 1217jdk** [comment]
추후 업데이트 할 예정입니다.

**Comment by sawol** [comment]
개발 완료하였습니다.
